### ISSUE TITLE
1.1 Release Roadmap

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#332]
My proposals for a 1.1 release.
#### Issues:
 - [x] #331 - Folder reorganization
 - [ ] #269, #321 - Add sanitize callback option
 - [ ] #256 - Edit link to post field
 - [x] #293 - Capabilities at the field level
 - [ ] #313 - Capabilities checks at the post level
 - [ ] #324 - Show titles attribute on groups
 - [x] #370 - Add hidden field type
 - [x] #372 - Add email field type
 - [x] #377 - Missing class_exists checks

#### PRs
 - [ ] #317 - Groups in groups
 - [x] #192 - Multi-checkbox field
 - [ ] #266 - Checkbox 0 value not saving (not sure if this is the best approach, but would like this fixed)

Is there anything else that should be added to this next release?

**Comment by mikeselander** [comment]
We will be releasing 1.1 shortly in the interest of fixing several bugs that are closed out on develop, but open master.
