### ISSUE TITLE
1.0.3 Release Roadmap

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#369]
It looks like it makes more sense to do a small bugfix/cleanup release before starting on some larger stuff for 1.1. I'm thinking these few fixes/adjustments for 1.0.3. I would like to get this release out next week.

 - [x] Fix repeatable fields bugs (props @barryceelen )
 - [x] Fix gmaps field  bug where key doesn't pass in correctly (props: @shadyvb )
 - [x] PHPUnit tests for repeatable fields
 - [x] Fix all minor WP VIP PHPCS errors/warning
 - [x] Write and complete inline documentation/dos blocks
 - [x] Minor adjustments to readme and add Pull Request template
 - [ ] Tag release, update version in files and document updates
