### ISSUE TITLE
1.2 Release Roadmap

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#388]
I'd like to split up 1.1 in the interest of keeping releases modular and ongoing and dedicate 1.2 to more architectural, larger decisions and pieces. There's a LOT of opportunity for architectural improvements and security/performance improvements and if we address these at once (or at least discuss them all in connection) the end result will be much, much better.

In fact, the more that I think of it we might need a backwards-compatibility breaking change for some of these. It would free us to really fix some of the underlying architectural issues and leapfrog ahead to being a much more flexible, modern field framework. thoughts anyone?

#### Issues: 
 - [ ] #384 - Namespaces and autoloading
 - [ ] #366 - Security Review
 - [ ] #325 - Support for register_meta
 - [ ] #314 - Composer install availability and config
 - [ ] #300 - CMB for user meta
 - [ ] #108 - CMB for options pages
 - [ ] #226 - Fix loading so it works in theme, plugin, or mu-plugin

#### PRs:
 - [ ] #249 - Date mods (we need a whole discussion on how to handle dates)

**Comment by mikeselander** [comment]
This issue is significantly out of date and the general roadmap for HMCMB has changed so closing this out.
